---
- name: Maintenance on TSE
  hosts: all

  vars:
      Message: Careful you need to updae your system

  tasks:
  - name: Ping TSE
    win_ping:

  - name: send msg
    win_shell: msg.exe /server:ADPL.local * "{{ Message }}"
