---
- name: Maintenance on TSE
  hosts: windows

  vars:
    ansible_user: Administrator
    ansible_password: Espoire15!
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    Message: Careful you need to updae your system

  tasks:
  - name: Ping TSE
    win_ping:

  - name: send msg
    win_shell: msg.exe /server:windows * "{{ Message }}"
