---
- name: Maintenance on TSE
  hosts: all

  vars_prompt:
    - name: "Message"
      prompt: "Enter your message"
      private: no
      default: "localhost"

  vars:
      Message: Toto

  tasks:
  - name: Ping TSE
    win_ping:

  - name: send msg
    win_shell: msg.exe /server:ADPL.local * "{{ Message }}"
