---
- name: Maintenance on TSE
  hosts: windows

  vars:
    ansible_user=Administrator
    ansible_password=Espoire15!
    ansible_connection=winrm
    Message: Careful you need to updae your system

  tasks:
  - name: Ping TSE
    win_ping:

  - name: send msg
    win_shell: msg.exe /server:192.168.108.124 * "{{ Message }}"
